<a href="https://colab.research.google.com/github/cys0420/2022/blob/main/20220316.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3]) 
print(x)
print(type(x))
print(x.shape)   # 3개짜리 array

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [3]:
x = np.arange(0,10,2)  #0부터 10까지 2의 간격으로 (10포함x)
print(x)
print(type(x))
print(x.shape)

[0 2 4 6 8]
<class 'numpy.ndarray'>
(5,)


In [6]:
x = np.linspace(0,10,6)  # 등분하여 숫자 6개(10포함)
print(x)
print(type(x))
print(x.shape)

[ 0.  2.  4.  6.  8. 10.]
<class 'numpy.ndarray'>
(6,)


In [5]:
x = np.array([[1,2,3], [4,5,6]]) #1,2,3
                                 #4,5,6
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [7]:
x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])  #[]개는 3-Dim.
print(x)
print(type(x))
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [8]:
x = np.ones([2, 2, 3]) #1로 채움/ (높이)x(행)x(열)
print(x)
print(type(x))
print(x.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
x = np.zeros([2, 2, 3])  #0으로 채움
print(x)
print(type(x))
print(x.shape)
x.reshape(3,2,2)

In [ ]:
np.random.normal(0, 1, [2,3,4])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.random.normal(0, 1, 100)
print(x)
plt.hist(x, bins=10)

In [ ]:
plt.figure()

theta1 = np.linspace(0, 2*np.pi, 100)
s1 = np.sin(theta1)
theta2 = np.linspace(0, 2*np.pi, 100) + np.pi/2
s2 = np.sin(theta2)

plt.subplot(2, 1, 1) # (rows, columns, panel number)
plt.plot(theta1, s1, '.')
plt.subplot(2, 1, 2) # (rows, columns, panel number)
plt.plot(theta2, s2, '.')

In [ ]:
np.corrcoef(s1,s2)